# TODO: Need to fix dependency conflicts later
name: smartpixel-env
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy=2.2.6
  - pandas=2.3.3
  - scipy=1.15.3
  - scikit-learn=1.7.2
  - matplotlib=3.10.7
  - seaborn=0.13.2
  - networkx=3.4.2
  - pillow=11.3.0
  - psutil=7.1.0
  - tornado=6.5.2
  - jupyterlab
  - ipykernel
  - ipywidgets
  - pip

  - pytorch=2.8.0
  - torchvision=0.23.0
  # If you want GPU support with CUDA 12 from conda, uncomment:
  # - pytorch-cuda=12.1

  - pip:
      - arbolta @ file:///home/z.ling.865/smartpixel-brevitas/arbolta/crates/python_bindings
      - array-api-compat==1.12.0
      - asttokens==3.0.0
      - brevitas==0.12.1
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - dependencies==2.0.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - jedi==0.19.2
      - Jinja2==3.1.6
      - joblib==1.5.2
      - jupyter_client==8.6.3
      - jupyter_core==5.8.1
      - jupyterlab_widgets==3.0.15
      - kiwisolver==1.4.9
      - MarkupSafe==3.0.3
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - packaging==25.0
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.5.0
      - prompt_toolkit==3.0.52
      - pure_eval==0.2.3
      - Pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.1.0
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing_extensions==4.15.0
      - tzdata==2025.2
      - unfoldNd==0.2.3
      - wcwidth==0.2.14
      - widgetsnbextension==4.0.14
      - triton==3.4.0
      # NVIDIA CUDA wheels â€” if using conda CUDA, remove these
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
